<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function island_recruiting_menu() {
  $items = array();
  $items['welcome'] = array(
    'title' => ' ',
    'description' => 'Island Recruiting landing page',
    'type' => MENU_CALLBACK,
    'page callback' => 'island_recruiting_splash',
    'file' => 'includes/island_recruiting_splash.inc',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function island_recruiting_theme($existing, $type, $theme, $path) {
  return array(
    'island_recruiting_splash' => array(
      'template' => 'theme/island_recruiting_splash',
      'file' => 'theme/theme.inc',
      'variables' => array(),
    ),
  );
}

/**
 * Logs user in programatically
 *
 * @param string $username
 *   User's name
 * @param string $password
 *   User's password
 *
 * @return boolean
 *   Success or failure
 */
function island_recruiting_user_login_credentials($username, $password) {
  if ($uid = user_authenticate($username, $password)) {
    $form = array();
    $form_state = array('uid' => $uid);
    user_login_submit($form, $form_state);
    return true;
  }
  else {
    return false;
  }
}

